-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2025-11-14 22:59:56 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g



DROP TABLE T_NRON_ACESSO CASCADE CONSTRAINTS
;

DROP TABLE T_NRON_CATG_EMOCAO CASCADE CONSTRAINTS
;

DROP TABLE T_NRON_DEPARTAMENTO CASCADE CONSTRAINTS
;

DROP TABLE T_NRON_EMOCAO CASCADE CONSTRAINTS
;

DROP TABLE T_NRON_REGIST_EMOCAO CASCADE CONSTRAINTS
;

DROP TABLE T_NRON_RESP_FORMULARIO CASCADE CONSTRAINTS
;

DROP TABLE T_NRON_USUARIO CASCADE CONSTRAINTS
;

DROP SEQUENCE SEQ_NRON_USUARIO;

DROP SEQUENCE SEQ_NRON_DEPARTAMENTO;

DROP SEQUENCE SEQ_NRON_ACESSO;

DROP SEQUENCE SEQ_NRON_CATG_EMOCAO;

DROP SEQUENCE SEQ_NRON_EMOCAO;

DROP SEQUENCE SEQ_REGIST_EMOCAO;

DROP SEQUENCE SEQ_RESP_FORMULARIO;



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE T_NRON_ACESSO 
    ( 
     ID_ACESSO NUMBER (5)  NOT NULL , 
     TP_ACESSO VARCHAR2 (50 CHAR)  NOT NULL , 
     DS_ACESSO VARCHAR2 (255 CHAR)  NOT NULL 
    ) 
;

COMMENT ON COLUMN T_NRON_ACESSO.ID_ACESSO IS 'ID DO TIPO DE ACESSO' 
;

COMMENT ON COLUMN T_NRON_ACESSO.TP_ACESSO IS 'TIPO DE ACESSO
(CHECK) -> ''FUNCIONARIO'',''GESTOR'',''RH_CLEVEL''' 
;

COMMENT ON COLUMN T_NRON_ACESSO.DS_ACESSO IS 'DESCRICAO DO TIPO DE ACESSO' 
;

ALTER TABLE T_NRON_ACESSO 
    ADD CONSTRAINT T_NRON_ACESSO_PK PRIMARY KEY ( ID_ACESSO ) ;

CREATE TABLE T_NRON_CATG_EMOCAO 
    ( 
     ID_CATG_EMOCAO NUMBER (5)  NOT NULL , 
     NM_CATG_EMOCAO VARCHAR2 (30 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE T_NRON_CATG_EMOCAO 
    ADD CONSTRAINT CK_NM_CATG_EMOCAO
    CHECK (NM_CATG_EMOCAO IN ('NEGATIVA', 'NEUTRA', 'POSITIVA')) 
;

COMMENT ON COLUMN T_NRON_CATG_EMOCAO.ID_CATG_EMOCAO IS 'ID DA EMOCAO' 
;

COMMENT ON COLUMN T_NRON_CATG_EMOCAO.NM_CATG_EMOCAO IS 'NOME DA EMOCAO 
(CHECK) -> ''POSITIVA'', ''NEGATIVA'', ''NEUTRA''' 
;

ALTER TABLE T_NRON_CATG_EMOCAO 
    ADD CONSTRAINT T_NRON_CATG_EMOCAO_PK PRIMARY KEY ( ID_CATG_EMOCAO ) ;

CREATE TABLE T_NRON_DEPARTAMENTO 
    ( 
     ID_DEPARTAMENTO NUMBER (5)  NOT NULL , 
     NM_DEPARTAMENTO VARCHAR2 (100 CHAR)  NOT NULL , 
     DS_DEPARTAMENTO VARCHAR2 (150 CHAR)  NOT NULL 
    ) 
;

COMMENT ON COLUMN T_NRON_DEPARTAMENTO.ID_DEPARTAMENTO IS 'ID DO DEPARTAMENTO' 
;

COMMENT ON COLUMN T_NRON_DEPARTAMENTO.NM_DEPARTAMENTO IS 'NOME DO DEPARTAMENTO' 
;

COMMENT ON COLUMN T_NRON_DEPARTAMENTO.DS_DEPARTAMENTO IS 'DESCRICAO DO DEPARTAMENTO' 
;

ALTER TABLE T_NRON_DEPARTAMENTO 
    ADD CONSTRAINT T_NRON_DEPARTAMENTO_PK PRIMARY KEY ( ID_DEPARTAMENTO ) ;

CREATE TABLE T_NRON_EMOCAO 
    ( 
     ID_EMOCAO      NUMBER (5)  NOT NULL , 
     NM_EMOCAO      VARCHAR2 (30 CHAR)  NOT NULL , 
     COR_EMOCAO     VARCHAR2 (10 BYTE)  NOT NULL , 
     ID_CATG_EMOCAO NUMBER (5)  NOT NULL 
    ) 
;

COMMENT ON COLUMN T_NRON_EMOCAO.ID_EMOCAO IS 'ID DA EMOCAO' 
;

COMMENT ON COLUMN T_NRON_EMOCAO.NM_EMOCAO IS 'NOME DA EMOCAO' 
;

COMMENT ON COLUMN T_NRON_EMOCAO.COR_EMOCAO IS 'CÓDIGO HEXADECIMAL DA COR REFERENTE À ESSA EMOÇÃO' 
;

ALTER TABLE T_NRON_EMOCAO 
    ADD CONSTRAINT T_NRON_EMOCAO_PK PRIMARY KEY ( ID_EMOCAO ) ;

CREATE TABLE T_NRON_REGIST_EMOCAO 
    ( 
     ID_REGIST_EMOCAO  NUMBER (5)  NOT NULL , 
     INT_REGIST_EMOCAO NUMBER (3,1)  NOT NULL , 
     DS_REGIST_EMOCAO  VARCHAR2 (255 CHAR)  NOT NULL , 
     DT_REGIST_EMOCAO  DATE  NOT NULL , 
     ID_EMOCAO         NUMBER (5)  NOT NULL 
    ) 
;

ALTER TABLE T_NRON_REGIST_EMOCAO 
    ADD CONSTRAINT INT_REGIST_EMOCAO 
    CHECK (INT_REGIST_EMOCAO BETWEEN 0.0 AND 10.0) 
;

COMMENT ON COLUMN T_NRON_REGIST_EMOCAO.ID_REGIST_EMOCAO IS 'ID DO REGISTRO DE EMOCAO' 
;

COMMENT ON COLUMN T_NRON_REGIST_EMOCAO.INT_REGIST_EMOCAO IS 'INTENSIDADE DA EMOÇÃO PRINCIPAL (1 A 10)' 
;

COMMENT ON COLUMN T_NRON_REGIST_EMOCAO.DS_REGIST_EMOCAO IS 'DESCRICAO DO REGISTRO DE EMOCAO' 
;

COMMENT ON COLUMN T_NRON_REGIST_EMOCAO.DT_REGIST_EMOCAO IS 'DATA DO REGISTRO DE EMOCAO' 
;

ALTER TABLE T_NRON_REGIST_EMOCAO 
    ADD CONSTRAINT T_NRON_REGIST_EMOCAO_PK PRIMARY KEY ( ID_REGIST_EMOCAO ) ;

CREATE TABLE T_NRON_RESP_FORMULARIO 
    ( 
     ID_RESPOSTA      NUMBER (5)  NOT NULL , 
     DT_RESPOSTA      DATE  NOT NULL , 
     MOT_RESPOSTA     NUMBER (3,1)  NOT NULL , 
     FEL_RESPOSTA     NUMBER (3,1)  NOT NULL , 
     EST_RESPOSTA     NUMBER (3,1)  NOT NULL , 
     OBS_RESPOSTA     VARCHAR2 (250 CHAR)  NOT NULL , 
     SAU_MEN_RESPOSTA NUMBER (4,1)  NOT NULL , 
     PROB_RESPOSTA    NUMBER (6,3)  NOT NULL , 
     MOD_VER_RESPOSTA VARCHAR2 (20 CHAR)  NOT NULL , 
     DT_ANL_RESPOSTA  DATE  NOT NULL , 
     ID_USUARIO       NUMBER (5)  NOT NULL , 
     ID_REGIST_EMOCAO NUMBER (5)  NOT NULL 
    ) 
;

ALTER TABLE T_NRON_RESP_FORMULARIO 
    ADD CONSTRAINT CK_MOT_RESPOSTA 
    CHECK (MOT_RESPOSTA BETWEEN 0.0 AND 10.0) 
;

ALTER TABLE T_NRON_RESP_FORMULARIO 
    ADD CONSTRAINT CK_FEL_RESPOSTA 
    CHECK (FEL_RESPOSTA BETWEEN 0.0 AND 10.0) 
;

COMMENT ON COLUMN T_NRON_RESP_FORMULARIO.ID_RESPOSTA IS 'ID DA RESPOSTA DO FORMULARIO' 
;

COMMENT ON COLUMN T_NRON_RESP_FORMULARIO.DT_RESPOSTA IS 'DATA DA RESPOSTA DO FORMULARIO' 
;

COMMENT ON COLUMN T_NRON_RESP_FORMULARIO.MOT_RESPOSTA IS 'NIVEL DE MOTIVACAO' 
;

COMMENT ON COLUMN T_NRON_RESP_FORMULARIO.FEL_RESPOSTA IS 'NIVEL DE FELICIDADE ' 
;

COMMENT ON COLUMN T_NRON_RESP_FORMULARIO.EST_RESPOSTA IS 'NIVEL DE ESTRESSE ' 
;

COMMENT ON COLUMN T_NRON_RESP_FORMULARIO.OBS_RESPOSTA IS 'OBSERVAÇÕES DA RESPOSTA	' 
;

COMMENT ON COLUMN T_NRON_RESP_FORMULARIO.SAU_MEN_RESPOSTA IS 'ANÁLISE DE SAUDE MENTAL FEITA PELA IA' 
;

COMMENT ON COLUMN T_NRON_RESP_FORMULARIO.PROB_RESPOSTA IS 'CONFIANCA DO MODELO DE IA' 
;

COMMENT ON COLUMN T_NRON_RESP_FORMULARIO.MOD_VER_RESPOSTA IS 'VERSÃO DO MODELO DE IA' 
;

COMMENT ON COLUMN T_NRON_RESP_FORMULARIO.DT_ANL_RESPOSTA IS 'DATA DE ANALISE DA IA' 
;
CREATE UNIQUE INDEX T_NRON_RESP_FORMULARIO__IDX ON T_NRON_RESP_FORMULARIO 
    ( 
     ID_REGIST_EMOCAO ASC 
    ) 
;

ALTER TABLE T_NRON_RESP_FORMULARIO 
    ADD CONSTRAINT T_NRON_RESP_FORMULARIO_PK PRIMARY KEY ( ID_RESPOSTA ) ;

CREATE TABLE T_NRON_USUARIO 
    ( 
     ID_USUARIO      NUMBER (5)  NOT NULL , 
     NM_USUARIO            VARCHAR2 (150 CHAR)  NOT NULL ,
     EM_USUARIO      VARCHAR2 (150 CHAR)  NOT NULL , 
     SEN_HASH_USUARIO     VARCHAR2 (255 CHAR)  NOT NULL ,
     STT_USUARIO     CHAR (1)  NOT NULL , 
     DT_CADASTRO     DATE  NOT NULL , 
     ID_ACESSO       NUMBER (5)  NOT NULL , 
     ID_DEPARTAMENTO NUMBER (5)  NOT NULL 
    ) 
;

COMMENT ON COLUMN T_NRON_USUARIO.ID_USUARIO IS 'ID DO USUARIO' 
;

COMMENT ON COLUMN T_NRON_USUARIO.NM_USUARIO IS 'NOME DO USUARIO'
;

COMMENT ON COLUMN T_NRON_USUARIO.EM_USUARIO IS 'EMAIL DO USUARIO' 
;

COMMENT ON COLUMN T_NRON_USUARIO.SEN_HASH_USUARIO IS 'SENHA HASH DO USUARIO'
;

COMMENT ON COLUMN T_NRON_USUARIO.STT_USUARIO IS 'STATUS DO USUARIO
TRUE - USUARIO ATIVO
FALSE - USUARIO DESATIVADO' 
;

COMMENT ON COLUMN T_NRON_USUARIO.DT_CADASTRO IS 'DATA DE CADASTRO' 
;

ALTER TABLE T_NRON_USUARIO 
    ADD CONSTRAINT T_NRON_USUARIO_PK PRIMARY KEY ( ID_USUARIO ) ;

ALTER TABLE T_NRON_USUARIO 
    ADD CONSTRAINT UK_NRON_EM_USUARIO UNIQUE ( EM_USUARIO ) ;

ALTER TABLE T_NRON_USUARIO 
    ADD CONSTRAINT FK_ACESSO_USUARIO FOREIGN KEY 
    ( 
     ID_ACESSO
    ) 
    REFERENCES T_NRON_ACESSO 
    ( 
     ID_ACESSO
    ) 
;

ALTER TABLE T_NRON_EMOCAO 
    ADD CONSTRAINT FK_CATG_EMOCAO_EMOCAO FOREIGN KEY 
    ( 
     ID_CATG_EMOCAO
    ) 
    REFERENCES T_NRON_CATG_EMOCAO 
    ( 
     ID_CATG_EMOCAO
    ) 
;

ALTER TABLE T_NRON_USUARIO 
    ADD CONSTRAINT FK_DEPARTAMENTO_USUARIO FOREIGN KEY 
    ( 
     ID_DEPARTAMENTO
    ) 
    REFERENCES T_NRON_DEPARTAMENTO 
    ( 
     ID_DEPARTAMENTO
    ) 
;

ALTER TABLE T_NRON_REGIST_EMOCAO 
    ADD CONSTRAINT FK_EMOCAO_REGIST_EMOCAO FOREIGN KEY 
    ( 
     ID_EMOCAO
    ) 
    REFERENCES T_NRON_EMOCAO 
    ( 
     ID_EMOCAO
    ) 
;

ALTER TABLE T_NRON_RESP_FORMULARIO 
    ADD CONSTRAINT FK_REGIST_EMOCAO_RESP_FORM FOREIGN KEY 
    ( 
     ID_REGIST_EMOCAO
    ) 
    REFERENCES T_NRON_REGIST_EMOCAO 
    ( 
     ID_REGIST_EMOCAO
    ) 
;

ALTER TABLE T_NRON_RESP_FORMULARIO 
    ADD CONSTRAINT FK_USUARIO_RESP_FORM FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES T_NRON_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

ALTER TABLE T_NRON_RESP_FORMULARIO
DROP CONSTRAINT FK_USUARIO_RESP_FORM;


ALTER TABLE T_NRON_RESP_FORMULARIO
ADD CONSTRAINT FK_USUARIO_RESP_FORM
FOREIGN KEY (id_usuario)
REFERENCES T_NRON_USUARIO(id_usuario)
ON DELETE CASCADE;

CREATE SEQUENCE SEQ_NRON_USUARIO
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_NRON_DEPARTAMENTO
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_NRON_ACESSO
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_REGIST_EMOCAO
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;


CREATE SEQUENCE SEQ_RESP_FORMULARIO
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_RESP_CATG_EMOCAO
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_RESP_REGIST_EMOCAO
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_NRON_EMOCAO
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;
-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             2
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
